name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'yarn'
        cache-dependency-path: frontend/yarn.lock

    - name: Install dependencies
      working-directory: ./frontend
      run: yarn install --frozen-lockfile

    - name: Build
      working-directory: ./frontend
      run: yarn build
      env:
        PUBLIC_URL: https://bamiel2025.github.io/Geo-Expert
        REACT_APP_BACKEND_URL: ${{ secrets.REACT_APP_BACKEND_URL || 'http://localhost:8001' }}
        REACT_APP_GEMINI_API_KEY: ${{ secrets.REACT_APP_GEMINI_API_KEY }}

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      run: |
        # Clean up any existing gh-pages branch
        git branch -D gh-pages || true
        git push origin --delete gh-pages || true

        # Create and switch to gh-pages branch
        git checkout --orphan gh-pages
        git rm -rf .

        # Copy build files
        cp -r ./frontend/build/* .

        # Create .nojekyll to prevent Jekyll processing
        touch .nojekyll

        # Add and commit
        git add .
        git commit -m "Deploy to GitHub Pages"

        # Force push to gh-pages branch
        git push origin gh-pages --force

        # Go back to main branch
        git checkout main